# Generated by Django 2.0.7 on 2018-07-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('cant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=11)),
                ('number', models.PositiveIntegerField(default=0)),
                ('academic_year', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='lending',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.Student'),
        ),
    ]
