# Generated by Django 2.1.1 on 2018-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_student_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(blank=True, through='lending.Lending', to='lending.Book'),
        ),
    ]
