# Generated by Django 2.1.1 on 2018-12-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_auto_20181012_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('career', models.CharField(max_length=100, verbose_name='Carrera')),
                ('modality', models.CharField(max_length=2, verbose_name='Modalidad')),
                ('study_topic', models.CharField(max_length=3, verbose_name='Plan de estudio')),
                ('course', models.CharField(max_length=10, verbose_name='Curso')),
                ('semester', models.CharField(max_length=1, verbose_name='Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('bibliographic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.BibliographicPlan')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Gabriel Garcia Marquez', max_length=200, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.CharField(default='La Luz', max_length=100, verbose_name='Editorial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Año de publicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cant',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.PositiveIntegerField(default=1, verbose_name='Año académico'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ci',
            field=models.CharField(max_length=11, verbose_name='CI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='book',
            name='study_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lending.StudyTopic', verbose_name='Asignatura'),
            preserve_default=False,
        ),
    ]
