# Generated by Django 2.1.1 on 2018-12-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_auto_20181225_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographicplan',
            name='modality',
            field=models.CharField(choices=[('CD', 'Curso Regular Diurno'), ('CE', 'Curso por encuentro')], max_length=2, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='bibliographicplan',
            name='semester',
            field=models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], max_length=1, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='bibliographicplan',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto')], verbose_name='Año'),
        ),
    ]
