# Generated by Django 2.1.1 on 2018-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_auto_20181225_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliographicplan',
            name='study_topic',
        ),
        migrations.AddField(
            model_name='bibliographicplan',
            name='study_plan',
            field=models.CharField(default='E', max_length=3, verbose_name='Plan de estudio'),
            preserve_default=False,
        ),
    ]
