# Generated by Django 2.1.1 on 2019-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_auto_20181225_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographicplan',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto')], verbose_name='Año'),
        ),
    ]
