# Generated by Django 2.1.1 on 2019-03-13 12:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MOD', 'Moderador')], default='ADMIN', max_length=5, verbose_name='Ocupación'),
            preserve_default=False,
        ),
    ]
