# Generated by Django 2.1.1 on 2019-03-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190313_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MOD', 'Moderador')], default='MOD', max_length=5, verbose_name='Ocupación'),
        ),
    ]
